// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ukoksdbgtkhxyiseqyjl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVrb2tzZGJndGtoeHlpc2VxeWpsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIzMTQ1OTUsImV4cCI6MjA1Nzg5MDU5NX0.i-8xHQQRHkzrPjKgjyden41Y0_vnZUO3g7jRXE20Yw8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);